import 'package:depouygulama/class/urun.dart';

class Veritabani {
  static List<Urun> urunler=[
    Urun("Laptop", 5000, "Elektronik"),
    Urun("Telefon", 3000, "Elektronik"),
    Urun("Masa", 800, "Mobilya"),
    Urun("Sandalye", 400, "Mobilya"),
    Urun("Kamera", 2000, "Elektronik"),
    Urun("Bilgisayar", 7000, "Elektronik"),
    Urun("Monitor", 1500, "Elektronik"),
    Urun("Klavye", 250, "Elektronik"),
    Urun("Fare", 150, "Elektronik"),
    Urun("Yazıcı", 2500, "Elektronik"),
    Urun("Scanner", 800, "Elektronik"),
    Urun("Ses Sistemi", 3500, "Elektronik"),
    Urun("Kulaklık", 500, "Elektronik"),
    Urun("Mikrofon", 1200, "Elektronik"),
    Urun("Webcam", 600, "Elektronik"),
    Urun("Harici Disk", 1000, "Elektronik"),
    Urun("USB Hub", 300, "Elektronik"),
    Urun("Kabel", 50, "Aksesuar"),
    Urun("Powerbank", 400, "Elektronik"),
    Urun("Şarj Aleti", 200, "Elektronik"),
    Urun("Koltuk", 1200, "Mobilya"),
    Urun("Yatak", 2500, "Mobilya"),
    Urun("Dolap", 1800, "Mobilya"),
    Urun("Kitaplık", 900, "Mobilya"),
    Urun("Raf", 350, "Mobilya"),
    Urun("Ayna", 400, "Mobilya"),
    Urun("Sehpa", 600, "Mobilya"),
    Urun("Lampa", 500, "Aydınlatma"),
    Urun("Avize", 1500, "Aydınlatma"),
    Urun("Duvar Tablosu", 700, "Dekorasyon"),
    Urun("Perde", 300, "Tekstil"),
    Urun("Halı", 1000, "Tekstil"),
    Urun("Yasdık", 150, "Tekstil"),
    Urun("Battaniye", 200, "Tekstil"),
    Urun("Çarşaf", 100, "Tekstil"),
    Urun("Havlu", 50, "Tekstil"),
    Urun("Elbise", 250, "Giyim"),
    Urun("Pantolon", 300, "Giyim"),
    Urun("Gömlek", 200, "Giyim"),
    Urun("Ceket", 500, "Giyim"),
    Urun("Ayakkabı", 400, "Giyim"),
    Urun("Çorap", 30, "Giyim"),
    Urun("Şal", 150, "Aksesuar"),
    Urun("Eldiven", 80, "Aksesuar"),
    Urun("Bere", 60, "Aksesuar"),
    Urun("Kemer", 100, "Aksesuar"),
    Urun("Çanta", 350, "Aksesuar"),
    Urun("Cüzdan", 150, "Aksesuar"),
    Urun("Gözlük", 250, "Aksesuar"),
    Urun("Saat", 800, "Aksesuar"),
    Urun("Yüzük", 400, "Aksesuar"),
    Urun("Kolye", 300, "Aksesuar"),
    Urun("Bilezik", 250, "Aksesuar"),
    Urun("Küpe", 200, "Aksesuar"),
    Urun("Broş", 100, "Aksesuar"),
    Urun("Kitap", 80, "Kütüphane"),
    Urun("Defter", 25, "Kütüphane"),
    Urun("Kalem", 10, "Kütüphane"),
    Urun("Silgi", 5, "Kütüphane"),
    Urun("Cetvel", 15, "Kütüphane"),
    Urun("Makas", 20, "Kütüphane"),
    Urun("Yapıştırıcı", 15, "Kütüphane"),
    Urun("Okul Çantası", 200, "Aksesuar"),
    Urun("Spor Ayakkabı", 500, "Giyim"),
    Urun("Atkı", 70, "Aksesuar"),
    Urun("Kundura", 600, "Giyim"),
    Urun("Terlik", 100, "Giyim"),
    Urun("Sanalet", 120, "Giyim"),
    Urun("Çizme", 450, "Giyim"),
    Urun("Spor Elbisesi", 350, "Giyim"),
    Urun("Şort", 150, "Giyim"),
    Urun("Tişört", 100, "Giyim"),
    Urun("Sweatshirt", 250, "Giyim"),
    Urun("Kazak", 300, "Giyim"),
    Urun("Etek", 200, "Giyim"),
    Urun("Takım Elbise", 1200, "Giyim"),
    Urun("Kravat", 150, "Aksesuar"),
    Urun("Papyon", 120, "Aksesuar"),
    Urun("Yelek", 250, "Giyim"),
    Urun("Sobacı", 400, "Giyim"),
    Urun("Elbise Ayakkabısı", 700, "Giyim"),
    Urun("Çizme Terlik", 180, "Giyim"),
    Urun("Sucu Ayakkabı", 350, "Giyim"),
    Urun("Yürüyüş Ayakkabısı", 450, "Giyim"),
    Urun("Kayo Ayakkabısı", 280, "Giyim"),
    Urun("Voleybol Topu", 200, "Spor"),
    Urun("Futbol Topu", 150, "Spor"),
    Urun("Basketbol Topu", 180, "Spor"),
    Urun("Tenis Raket", 400, "Spor"),
    Urun("Badminton Raket", 250, "Spor"),
    Urun("Eğitim Malzemeleri", 500, "Eğitim"),
    Urun("Oyuncak Robot", 600, "Oyuncak"),
    Urun("Bebek Oyuncağı", 300, "Oyuncak"),
    Urun("Yapboz", 80, "Oyuncak"),
    Urun("Lego", 400, "Oyuncak"),
    Urun("Bebek Arabası", 1500, "Bebek"),
    Urun("Bebek Karyolası", 2000, "Bebek"),
    
  ];

  static void ekle(Urun urun){
    urunler.add(urun);
  }
}
